### ISSUE TITLE
TestEZ Folder Name

### ISSUE THREAD

**Issue by karl-police** [imezx/Warp#5]
GitHub showed this repository in my recommended 🤷 

Eitherways. Why is the TestEZ folder named TestEZ

I know this folder name, Roblox has stuff named like this internally. What's up with this? 🤔

**Comment by imezx** [comment]
i use roblox TestEZ to test the library most used functional that can be test with TestEZ. TestEZ folder is for roblox TestEZ modules to require.

**Comment by imezx** [comment]
im closing this.

**Comment by karl-police** [comment]
> i use roblox TestEZ to test the library most used functional that can be test with TestEZ. TestEZ folder is for roblox TestEZ modules to require.

The Storybook Plugin relies on a TestEZ folder. So how do these folders work, is it using a built in thing? Or is TestEZ a term?
